import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate as pgMigrate } from "drizzle-orm/node-postgres/migrator";
import type { PgDatabase, PgQueryResultHKT } from "drizzle-orm/pg-core";
import pg from "pg";
import * as schema from "./schema.js";

export * from "./schema.js";
export { schema };

/** Any Drizzle Postgres database with the SEPscope schema: node-postgres in production, PGlite in tests. */
export type Database = PgDatabase<PgQueryResultHKT, typeof schema>;

/** SQL migrations generated by drizzle-kit; resolves the same from src/ and dist/. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL("../drizzle", import.meta.url));

export interface DbConnection {
  db: Database;
  /** Applies any pending migrations. */
  migrate(): Promise<void>;
  close(): Promise<void>;
}

/** Arbitrary key for the advisory lock that serializes migrations across processes. */
export const MIGRATION_LOCK_ID = 7_340_105_001;

/** The part of pg.Pool that withAdvisoryLock needs. */
export interface LockablePool {
  connect(): Promise<{ query(text: string, values: unknown[]): Promise<unknown>; release(): void }>;
}

/** Runs `fn` while holding a session-level Postgres advisory lock on its own connection. */
export async function withAdvisoryLock<T>(pool: LockablePool, lockId: number, fn: () => Promise<T>): Promise<T> {
  const client = await pool.connect();
  try {
    await client.query("select pg_advisory_lock($1)", [lockId]);
    try {
      return await fn();
    } finally {
      await client.query("select pg_advisory_unlock($1)", [lockId]);
    }
  } finally {
    client.release();
  }
}

/** Connects to Postgres. The pool connects lazily, on the first query. */
export function createDb(databaseUrl: string): DbConnection {
  const pool = new pg.Pool({ connectionString: databaseUrl });
  const db = drizzle(pool, { schema });
  return {
    db,
    // The worker and the API both migrate on start; the lock stops them racing.
    migrate: () => withAdvisoryLock(pool, MIGRATION_LOCK_ID, () => pgMigrate(db, { migrationsFolder: MIGRATIONS_FOLDER })),
    close: () => pool.end(),
  };
}
