import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate as pgMigrate } from "drizzle-orm/node-postgres/migrator";
import type { PgDatabase, PgQueryResultHKT } from "drizzle-orm/pg-core";
import pg from "pg";
import * as schema from "./schema.js";

export * from "./schema.js";
export { schema };

/** Any Drizzle Postgres database with the SEPscope schema: node-postgres in production, PGlite in tests. */
export type Database = PgDatabase<PgQueryResultHKT, typeof schema>;

/** SQL migrations generated by drizzle-kit; resolves the same from src/ and dist/. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL("../drizzle", import.meta.url));

export interface DbConnection {
  db: Database;
  /** Applies any pending migrations. */
  migrate(): Promise<void>;
  close(): Promise<void>;
}

/** Connects to Postgres. The pool connects lazily, on the first query. */
export function createDb(databaseUrl: string): DbConnection {
  const pool = new pg.Pool({ connectionString: databaseUrl });
  const db = drizzle(pool, { schema });
  return {
    db,
    migrate: () => pgMigrate(db, { migrationsFolder: MIGRATIONS_FOLDER }),
    close: () => pool.end(),
  };
}
